import mongoose from 'mongoose';
import User from '../models/User.model.js';
import StudentProfile from '../models/StudentProfile.model.js';
import TeacherProfile from '../models/TeacherProfile.model.js';
import Class from '../models/Class.model.js';
import { hashPassword } from '../utils/hashUtils.js';
import { parsePagination, buildPaginationMeta, buildSearchRegex } from '../utils/paginationHelper.js';
import ERROR_CODES from '../constants/errorCodes.js';
import { resetStudentPassword as resetPassword } from './studentPassword.service.js';
import { buildStudentCredentials } from '../utils/studentCredentials.js';

/** Helper: throw a structured app error */
const appError = (message, statusCode, errorCode) => {
  const err = new Error(message);
  err.statusCode = statusCode;
  err.errorCode = errorCode;
  return err;
};

/**
 * Create a student account, profile, and class membership atomically.
 * Credentials are generated by the API and returned only in this response.
 */
const createStudent = async (data) => {
  const { name, email, phone, admissionNo, classId, rollNo, dob, guardianName, guardianPhone, address, gender } = data;

  const existingAdmission = await StudentProfile.findOne({ admissionNo });
  if (existingAdmission) throw appError('Admission number already in use', 409, ERROR_CODES.DUPLICATE_ENTRY);

  const classDoc = await Class.findOne({ _id: classId, isDeleted: false });
  if (!classDoc) throw appError('Class not found', 404, ERROR_CODES.NOT_FOUND);

  let credentials = null;
  for (let attempt = 0; attempt < 10; attempt += 1) {
    const candidate = buildStudentCredentials(name);
    const exists = await User.exists({ username: candidate.username });
    if (!exists) {
      credentials = candidate;
      break;
    }
  }
  if (!credentials) throw appError('Could not generate a unique username. Please try again.', 503, ERROR_CODES.INTERNAL_ERROR);

  const passwordHash = await hashPassword(credentials.password);
  const session = await mongoose.startSession();
  let createdUser;
  let createdProfile;
  try {
    await session.withTransaction(async () => {
      [createdUser] = await User.create([{
        role: 'student',
        username: credentials.username,
        passwordHash,
        name,
        email: email || undefined,
        phone: phone || undefined,
        status: 'active',
        firstPasswordChange: false,
      }], { session });

      [createdProfile] = await StudentProfile.create([{
        userId: createdUser._id,
        admissionNo,
        rollNo,
        classId: classDoc._id,
        section: classDoc.section,
        dob: dob ? new Date(dob) : undefined,
        guardianName,
        guardianPhone,
        address,
        gender,
      }], { session });

      const classUpdate = await Class.updateOne(
        { _id: classDoc._id, isDeleted: false },
        { $addToSet: { studentIds: createdUser._id } },
        { session }
      );
      if (classUpdate.matchedCount !== 1) {
        throw appError('Class is no longer available', 409, ERROR_CODES.VALIDATION_ERROR);
      }
    });
  } finally {
    await session.endSession();
  }

  const safeUser = createdUser.toObject();
  delete safeUser.passwordHash;
  return { user: safeUser, profile: createdProfile, credentials };
};

/**
 * Create a teacher user + profile.
 */
const createTeacher = async (data) => {
  const { username, password, name, email, phone, employeeId, subjects, qualification, joiningDate } = data;

  const existing = await User.findOne({ username });
  if (existing) throw appError('Username already taken', 409, ERROR_CODES.DUPLICATE_ENTRY);

  const existingEmployee = await TeacherProfile.findOne({ employeeId });
  if (existingEmployee) throw appError('Employee ID already in use', 409, ERROR_CODES.DUPLICATE_ENTRY);

  const passwordHash = await hashPassword(password);
  const user = await User.create({ role: 'teacher', username, passwordHash, name, email: email || undefined, phone, status: 'active' });

  try {
    const profile = await TeacherProfile.create({
      userId: user._id, employeeId,
      subjects: subjects || [],
      qualification,
      joiningDate: joiningDate ? new Date(joiningDate) : undefined,
    });
    return { user, profile };
  } catch (err) {
    await User.findByIdAndDelete(user._id);
    throw err;
  }
};

/**
 * List users with pagination, search, filter by status/role.
 */
const listUsers = async (query, roleFilter = null) => {
  const { page, limit, skip, sortBy, sortOrder } = parsePagination(query, ['name', 'username', 'status', 'createdAt']);
  const { search, status } = query;

  const filter = { status: { $ne: 'deleted' } };
  if (roleFilter) filter.role = roleFilter;
  if (status) filter.status = status;
  if (search) {
    const searchRegex = buildSearchRegex(search);
    filter.$or = [
      { name: searchRegex },
      { username: searchRegex },
      { email: searchRegex },
      { phone: searchRegex },
    ];
  }

  const [users, total] = await Promise.all([
    User.find(filter).sort({ [sortBy]: sortOrder }).skip(skip).limit(limit),
    User.countDocuments(filter),
  ]);

  return { users, pagination: buildPaginationMeta(total, page, limit) };
};

/**
 * Get a single user by ID with their profile.
 */
const getUserById = async (userId) => {
  const user = await User.findOne({ _id: userId, status: { $ne: 'deleted' } });
  if (!user) throw appError('User not found', 404, ERROR_CODES.NOT_FOUND);

  let profile = null;
  if (user.role === 'student') {
    profile = await StudentProfile.findOne({ userId });
  } else if (user.role === 'teacher') {
    profile = await TeacherProfile.findOne({ userId });
  }

  return { user, profile };
};

/**
 * Update student core fields + profile fields.
 */
const updateStudent = async (userId, data) => {
  const { name, email, phone, rollNo, section, dob, guardianName, guardianPhone, address, gender } = data;

  const user = await User.findOne({ _id: userId, role: 'student', status: { $ne: 'deleted' } });
  if (!user) throw appError('Student not found', 404, ERROR_CODES.NOT_FOUND);

  const userUpdates = {};
  if (name)  userUpdates.name  = name;
  if (email) userUpdates.email = email;
  if (phone) userUpdates.phone = phone;

  const profileUpdates = {};
  if (rollNo        !== undefined) profileUpdates.rollNo        = rollNo;
  if (section       !== undefined) profileUpdates.section       = section;
  if (dob           !== undefined) profileUpdates.dob           = new Date(dob);
  if (guardianName  !== undefined) profileUpdates.guardianName  = guardianName;
  if (guardianPhone !== undefined) profileUpdates.guardianPhone = guardianPhone;
  if (address       !== undefined) profileUpdates.address       = address;
  if (gender        !== undefined) profileUpdates.gender        = gender;

  const [updatedUser, updatedProfile] = await Promise.all([
    Object.keys(userUpdates).length ? User.findByIdAndUpdate(userId, userUpdates, { returnDocument: 'after' }) : user,
    Object.keys(profileUpdates).length ? StudentProfile.findOneAndUpdate({ userId }, profileUpdates, { returnDocument: 'after', upsert: true }) : StudentProfile.findOne({ userId }),
  ]);

  return { user: updatedUser, profile: updatedProfile };
};

/**
 * Update teacher core fields + profile fields.
 */
const updateTeacher = async (userId, data) => {
  const { name, email, phone, subjects, qualification, joiningDate } = data;

  const user = await User.findOne({ _id: userId, role: 'teacher', status: { $ne: 'deleted' } });
  if (!user) throw appError('Teacher not found', 404, ERROR_CODES.NOT_FOUND);

  const userUpdates = {};
  if (name)  userUpdates.name  = name;
  if (email) userUpdates.email = email;
  if (phone) userUpdates.phone = phone;

  const profileUpdates = {};
  if (subjects      !== undefined) profileUpdates.subjects      = subjects;
  if (qualification !== undefined) profileUpdates.qualification = qualification;
  if (joiningDate   !== undefined) profileUpdates.joiningDate   = new Date(joiningDate);

  const [updatedUser, updatedProfile] = await Promise.all([
    Object.keys(userUpdates).length ? User.findByIdAndUpdate(userId, userUpdates, { returnDocument: 'after' }) : user,
    Object.keys(profileUpdates).length ? TeacherProfile.findOneAndUpdate({ userId }, profileUpdates, { returnDocument: 'after', upsert: true }) : TeacherProfile.findOne({ userId }),
  ]);

  return { user: updatedUser, profile: updatedProfile };
};

/**
 * Soft-delete a user (set status to deleted).
 * Does NOT remove profile records.
 */
const deleteUser = async (userId) => {
  const user = await User.findOne({ _id: userId, status: { $ne: 'deleted' } });
  if (!user) throw appError('User not found', 404, ERROR_CODES.NOT_FOUND);
  await User.findByIdAndUpdate(userId, { status: 'deleted' });
};

/**
 * Block a user account.
 */
const blockUser = async (userId) => {
  const user = await User.findOne({ _id: userId, status: { $ne: 'deleted' } });
  if (!user) throw appError('User not found', 404, ERROR_CODES.NOT_FOUND);
  if (user.status === 'blocked') throw appError('User is already blocked', 400, ERROR_CODES.DUPLICATE_ENTRY);
  await User.findByIdAndUpdate(userId, { status: 'blocked' });
};

/**
 * Unblock a user account.
 */
const unblockUser = async (userId) => {
  const user = await User.findOne({ _id: userId, status: 'blocked' });
  if (!user) throw appError('User not found or not blocked', 404, ERROR_CODES.NOT_FOUND);
  await User.findByIdAndUpdate(userId, { status: 'active' });
};

const resetStudentPassword = async (studentId) => resetPassword(studentId);

export { createStudent, createTeacher, listUsers, getUserById, updateStudent, updateTeacher, deleteUser, blockUser, unblockUser, resetStudentPassword };
export default { createStudent, createTeacher, listUsers, getUserById, updateStudent, updateTeacher, deleteUser, blockUser, unblockUser, resetStudentPassword };
