const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  REFRESH_TOKEN_REUSE: 'REFRESH_TOKEN_REUSE',
  UNAUTHORIZED: 'UNAUTHORIZED',
  SCOPE_VIOLATION: 'SCOPE_VIOLATION',
  NOT_FOUND: 'NOT_FOUND',
  ACCOUNT_BLOCKED: 'ACCOUNT_BLOCKED',
  UPLOAD_FAILED: 'UPLOAD_FAILED',
  NOTIFICATION_FAILED: 'NOTIFICATION_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
};

export default ERROR_CODES;
